# Generated by Django 4.2.1 on 2023-05-20 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stock_monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="symbol",
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="stocks",
            field=models.ManyToManyField(to="stock_monitoring.stock"),
        ),
    ]
